PMU Simulator: function.c File Reference
function.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <dirent.h>
#include <sys/wait.h>
#include "function.h"
#include "ServerFunction.h"
Macros
#define channel_name 100
Functions
void B_copy (unsigned char main[], unsigned char tmp[], int ind, int n)
void copy_cbyc (unsigned char dst[], unsigned char *s, int size)
char * measurement_Return ()
void H2S (char a[], unsigned char temp_6[])
void i2c (int t, unsigned char temp[])
void li2c (long int t1, unsigned char temp_1[])
void f2c (float f, unsigned char temp_1[])
int c2i (unsigned char temp[])
long int c2li (unsigned char temp_3[])
uint16_t compute_CRC (unsigned char *message, int length)
void sigchld_handler (int s)
int isNthBitSet (unsigned char c, int n)
unsigned int to_intconvertor (unsigned char array[])
void long_int_to_ascii_convertor (unsigned long int n, unsigned char hex[])
void int_to_ascii_convertor (unsigned int n, unsigned char hex[])
int ncmp_cbyc (unsigned char dst[], unsigned char src[], int size)
void byte_by_byte_copy (unsigned char dst[], unsigned char src[], int index, int n)
unsigned long int to_long_int_convertor (unsigned char array[])
unsigned int to_long_int_convertor1 (unsigned char array[])
Macro Definition Documentation
channel_name
#define channel_name 100
Definition at line 69 of file function.c.
Function Documentation
B_copy()
void B_copy (unsigned char main[], unsigned char tmp[], int ind, int n)
FUNCTION B_copy(unsigned char main[], unsigned char tmp[], int ind, int n):
Function copies unsigned char or Bytes in a main array from tmp array.
Definition at line 75 of file function.c.
 {
         int k;
         for(k=0; k<n; k++)
         {
                 main[ind+k] = tmp[k];
         }
 };
References main(), and n.
Referenced by create_cfg(), generate_data_frame(), header_frm_gen(), and reconfig_cfg_CC().
byte_by_byte_copy()
void byte_by_byte_copy (unsigned char dst[], unsigned char src[], int index, int n)
Definition at line 313 of file function.c.
{
         int i;
         for(i = 0;i<n; i++)
                 dst[index + i] = src[i];
 }
References i, and n.
Referenced by tcp_send_dr_data().
c2i()
int c2i (unsigned char temp[])
FUNCTION c2i (unsigned char temp[]):
Function for unsigned Character to Integer Conversion
Definition at line 178 of file function.c.
 {
         int i;
         i = temp[0];
         i<<=8;
         i |=temp[1];
         return(i);
 }
References i, and temp.
Referenced by create_cfg(), create_fifo_buffer(), create_pmu_model(), frame_size(), SEND_DATA(), sendTCPCFGFrame(), TCP_CONNECTIONS(), and UDP_PMU().
c2li()
long int c2li (unsigned char temp_3[])
FUNCTION c2li (unsigned char temp_3[]):
Function for unsigned Character to Long Integer Conversion
Definition at line 192 of file function.c.
 {
         long int i;
         unsigned char a[4];
         memset(a, '\0', 4);
         strcpy((char *)a, (char *)temp_3);
         i = a[0];
         i<<=8;
         i |=a[1];
         i<<=8;
         i |=a[2];
         i<<=8;
         i |=a[3];
         return(i);
 }
References i.
Referenced by TCP_CONNECTIONS().
compute_CRC()
uint16_t compute_CRC (unsigned char * message, int length)
FUNCTION uint16_t compute_CRC(unsigned char *message,char length):
Function for calculation of CHECKSUM CRC-CCITT (0xffff) of string of
unsigned Character.
Definition at line 214 of file function.c.
 {
         uint16_t crc=0x0ffff,temp,quick;
         int i;
         for(i=0;i<length;i++)
         {
                 temp=(crc>>8)^message[i];
                 crc<<=8;
                 quick=temp ^ ( temp >>4);
                 crc ^=quick;
                 quick<<=5;
                 crc ^=quick;
                 quick <<=7;
                 crc ^= quick;
         }
         return crc;
 }
References i, and temp.
Referenced by create_cfg(), generate_data_frame(), header_frm_gen(), reconfig_cfg_CC(), and tcp_send_dr_data().
copy_cbyc()
void copy_cbyc (unsigned char dst[], unsigned char * s, int size)
Definition at line 87 of file function.c.
{
         int i;
         for(i = 0; i< size; i++)
                 dst[i] = *(s + i);
 }
References i.
Referenced by TCP_CONNECTIONS().
f2c()
void f2c (float f, unsigned char temp_1[])
FUNCTION li2c (long int t1, unsigned char temp_1[]):
Function for float to unsigned Character Conversion
Definition at line 160 of file function.c.
 {
         int i, j;
         float fv;
         unsigned char a1[sizeof fv];
         fv = f;
         memcpy(a1, &fv, sizeof fv);
         for (i=0, j=3; i<sizeof fv; i++, j--)
         {
                 temp_1[j] = a1[i];
         }
 }
References f, i, j, and temp_1.
Referenced by generate_data_frame().
H2S()
void H2S (char a[], unsigned char temp_6[])
FUNCTION H2S(char a[], unsigned char temp_6[]):
Function for unsigned/Hexa char to String Conversion.
Definition at line 120 of file function.c.
 {
         int k;
         for(k=0; k<16; k++)
         {
                 a[k] = temp_6[k];
         }
         a[16] = '\0';
 }
References temp_6.
i2c()
void i2c (int t, unsigned char temp[])
FUNCTION i2c (int t, unsigned char temp[]):
Function for Integer to unsigned Character Conversion
Definition at line 137 of file function.c.
 {
         temp[0] = t>>8;
         temp[1] = t;
 }
References temp.
Referenced by create_cfg(), generate_data_frame(), header_frm_gen(), and reconfig_cfg_CC().
int_to_ascii_convertor()
void int_to_ascii_convertor (unsigned int n, unsigned char hex[])
Definition at line 283 of file function.c.
{
         hex[0] = n >> 8;
         hex[1] = n ;
 }
References n.
Referenced by tcp_send_dr_data().
isNthBitSet()
int isNthBitSet (unsigned char c, int n)
FUNCTION isNthBitSit(unsigned char c, int n):
Function to check if nth bit is set in char c
Definition at line 245 of file function.c.
{
     static unsigned char mask[] = {1, 2, 4, 8, 16, 32, 63, 128};
     return ((c & mask[n]) != 0);
 }
References n.
Referenced by create_pmu_model().
li2c()
void li2c (long int t1, unsigned char temp_1[])
FUNCTION li2c (long int t1, unsigned char temp_1[]):
Function for Long Integer to unsigned Character Conversion.
Definition at line 147 of file function.c.
 {
         temp_1[0] = t1>>24;
         temp_1[1] = t1>>16;
         temp_1[2] = t1>>8;
         temp_1[3] = t1;
 }
References t1, and temp_1.
Referenced by create_cfg(), generate_data_frame(), header_frm_gen(), and reconfig_cfg_CC().
long_int_to_ascii_convertor()
void long_int_to_ascii_convertor (unsigned long int n, unsigned char hex[])
Definition at line 270 of file function.c.
{
         hex[0] = n >> 24;
         hex[1] = n >> 16;
         hex[2] = n >> 8;
         hex[3] = n ;
 }
References n.
Referenced by tcp_send_dr_data().
measurement_Return()
char* measurement_Return ()
FUNCTION char* measurement_Return ():
Function to read the measurement file and return all measurements values for a singel timestamp.
Definition at line 98 of file function.c.
 {
         char *l1;
         size_t l2 = 0;
         ssize_t result;
         while(1)
         {
                 while ((result = getdelim (&l1, &l2, ('\n'), fp_DataFile)) >0)
                 {
                         return l1;
                 }
                 fseek(fp_DataFile, 0, SEEK_SET);
                 result = 1;
         }
         fclose(fp_DataFile);
 }
References fp_DataFile.
Referenced by generate_data_frame().
ncmp_cbyc()
int ncmp_cbyc (unsigned char dst[], unsigned char src[], int size)
Definition at line 294 of file function.c.
{
         int i,flag = 0;
         for(i = 0; i< size; i++)        {
                 if(dst[i] != src[i]) {
                         flag = 1;//FUNCTION
                         break;
                 }
         }
         return flag;
 }
References i.
sigchld_handler()
void sigchld_handler (int s)
FUNCTION sigchld_handler(int s):
Function for TCP connection signal handling
Definition at line 236 of file function.c.
 {
         while(wait(NULL) > 0);
 }
Referenced by start_server().
to_intconvertor()
unsigned int to_intconvertor (unsigned char array[])
Definition at line 256 of file function.c.
{
         unsigned int n;
         n = array[0];
         n <<= 8;
         n |= array[1];
         return n;
 }
References n.
to_long_int_convertor()
unsigned long int to_long_int_convertor (unsigned char array[])
Definition at line 325 of file function.c.
{
         unsigned long int n;
         n = array[0];
         n <<= 8;
         n |= array[1];
         n <<= 8;
         n |= array[2];
         n <<= 8;
         n |= array[3];
         return n;
 }
References n.
to_long_int_convertor1()
unsigned int to_long_int_convertor1 (unsigned char array[])
Definition at line 345 of file function.c.
{
         unsigned int n;
 /*      n = array[0];
         n <<= 8;
         n |= array[1];
         n <<= 8;
         n |= array[2];
         n <<= 8;
         //n |= 0;
 */
         n = array[0] <<16;
         n |= array[1] << 8;
         n |= array[2];
         return n;
 }
References n.