iPDC - (Phasor Data Concentrator): convertComtrade.m File Reference
convertComtrade.m File Reference
Functions
if isempty (Path) Path
PathAndCfgNameNew (end)
PathAndDatNameNew (end)
if ~ischar (temp_string)
end fclose (cfg_id)
fseek (dat_id, 0,-1) = fopen(PathAndDatNameNew,'w')
place at start dat (1:2,:)
fseek (dat_id, 8,-1)
place at first analog data dat (3:2+NR1, 1:l)
place at first digital data dat (3+NR1:2+NR1+NR2, 1:l)
end fclose (dat_id)
dat (:, k)
fwrite (dat_id, dat([1:2], 1), '2 *uint32', 0, 'ieee-le')
fwrite (dat_id, dat([3:NR1+2], 1),[num2str(NR1),' *int16'], 0, 'ieee-le')
fwrite (dat_id, dat([2+NR1+1:end], 1),[num2str(NR2),' *uint16'], 0, 'ieee-le')
fwrite (dat_id, dat([1:2], 2:end), '2 *uint32', 2 *(NR1+NR2), 'ieee-le')
fseek (dat_id, 8+2 *NR1,-1)
fwrite (dat_id, dat([3:NR1+2], 2:end),[num2str(NR1),' *int16'],(2 *NR2+8), 'ieee-le')
fseek (dat_id, 8+2 *(NR1+NR2),-1)
fwrite (dat_id, dat([2+NR1+1:end], 2:end),[num2str(NR2),' *uint16'],(2 *NR1+8), 'ieee-le')
flineprint (cfg_id, cfg_string(1, k))
function flineprint (FID, in) kk
end fprintf (FID,'%s\n', in{1}{kk})
while ~isempty (rem)[out
if (string(i)==delimiters) i
while (~any(string(i)==delimiters)) i
if (i > len)
Variables
function []
PathAndCfgName =[Path CfgFileName]
DatFileName = strcat(CfgFileName(1:length(CfgFileName)-4), '.dat')
PathAndDatName =[Path DatFileName]
end [Path, File, Ext] = fileparts(PathAndCfgName)
cfg_id = fopen(PathAndCfgName,'r')
dat_id = fopen(PathAndDatName,'r')
cfg_string = cell([1,50])
k =1
while temp_string = fgetl(cfg_id)
if break
Ana_Ch = sscanf(char(cfg_string{1,2}(2)),'%d')
Dig_Ch = sscanf(char(cfg_string{1,2}(3)),'%d')
NR1 = Ana_Ch
NR2 = ceil(Dig_Ch/16)
l = size(dat,2)
dat = dat'
a = max(abs(dat(:,k)-b))/2^15
function out
rem = strtok_singleDlm(rem,dlm)
len = length(string)
i = 1
end start = i
end end finish = i - 1
token = string(start:finish)
remainder = string(finish +1:len)
Function Documentation
dat() [1/4]
place at start dat (1:2 , :)
dat() [2/4]
place at first digital data dat (3+NR1:2+NR1+ NR2, 1:l)
dat() [3/4]
place at first analog data dat (3:2+ NR1, 1:l)
dat() [4/4]
dat (: , k)
fclose() [1/2]
end fclose (cfg_id)
Referenced by cfgparser(), closefilestreams(), dataWriteInFile(), makecomtradecfg(), recreate_cfg_objects(), remove_old_cfg(), and updatecomtradecfg().
fclose() [2/2]
end fclose (dat_id)
flineprint() [1/2]
flineprint (cfg_id , cfg_string(1, k))
flineprint() [2/2]
function flineprint (FID , in)
fprintf()
end fprintf (FID , '%s\n' , in{1}{kk})
Referenced by dataWriteInFile(), main(), makecomtradecfg(), and updatecomtradecfg().
fseek() [1/4]
fseek (dat_id , 0 , - 1) = fopen(PathAndDatNameNew,'w')
Referenced by cfgparser(), recreate_cfg_objects(), remove_old_cfg(), and updatecomtradecfg().
fseek() [2/4]
fseek (dat_id , 8+2 * NR1+NR2, - 1)
fseek() [3/4]
fseek (dat_id , 8+2 * NR1, - 1)
fseek() [4/4]
fseek (dat_id , 8 , - 1)
fwrite() [1/6]
fwrite (dat_id , dat([1:2], 1) , '2 *uint32' , 0 , 'ieee-le')
Referenced by cfgparser(), dataparser(), and remove_old_cfg().
fwrite() [2/6]
fwrite (dat_id , dat([1:2], 2:end) , '2 *uint32' , 2 * NR1+NR2, 'ieee-le')
fwrite() [3/6]
fwrite (dat_id , dat([2+NR1+1:end], 1) , 0 , 'ieee-le')
fwrite() [4/6]
fwrite (dat_id , dat([2+NR1+1:end], 2:end) , (2 *NR1+8) , 'ieee-le')
fwrite() [5/6]
fwrite (dat_id , dat([3:NR1+2], 1) , 0 , 'ieee-le')
fwrite() [6/6]
fwrite (dat_id , dat([3:NR1+2], 2:end) , (2 *NR2+8) , 'ieee-le')
if() [1/2]
if (i , len)
if() [2/2]
if (string(i) = =delimiters)
isempty()
if isempty (Path)
PathAndCfgNameNew()
PathAndCfgNameNew (end)
PathAndDatNameNew()
PathAndDatNameNew (end)
while()
while (~ anystring(i)==delimiters)
~ischar()
if ~ischar (temp_string)
~isempty()
while ~isempty (rem)
Definition at line 122 of file convertComtrade.m.
             {k},rem] = strtok_singleDlm(rem,dlm);
Variable Documentation
a
a = max(abs(dat(:,k)-b))/2^15
Definition at line 79 of file convertComtrade.m.
Referenced by dataWriteInFile(), and makecomtradecfg().
Ana_Ch
Ana_Ch = sscanf(char(cfg_string{1,2}(2)),'%d')
Definition at line 59 of file convertComtrade.m.
break
break
Definition at line 54 of file convertComtrade.m.
cfg_id
cfg_id = fopen(PathAndCfgName,'r')
Definition at line 48 of file convertComtrade.m.
cfg_string
if end cfg_string = cell([1,50])
Definition at line 50 of file convertComtrade.m.
dat
end dat = dat'
Definition at line 74 of file convertComtrade.m.
dat_id
dat_id = fopen(PathAndDatName,'r')
Definition at line 49 of file convertComtrade.m.
DatFileName
DatFileName = strcat(CfgFileName(1:length(CfgFileName)-4), '.dat')
Definition at line 32 of file convertComtrade.m.
Dig_Ch
Dig_Ch = sscanf(char(cfg_string{1,2}(3)),'%d')
Definition at line 60 of file convertComtrade.m.
end
end[status, PathAndCfgNameNew] = fileparts(PathAndCfgName)
Definition at line 36 of file convertComtrade.m.
finish
end end finish = i - 1
Definition at line 140 of file convertComtrade.m.
function
end Subfunction strtok_singleDlm A specelization of the default strtok function
Initial value:
= convertComtrade (PathAndCfgName)
    if nargin == 0
        [CfgFileName,Path] = uigetfile('*.cfg')
Definition at line 27 of file convertComtrade.m.
i
i = 1
Definition at line 131 of file convertComtrade.m.
Referenced by cfgparser(), copy_cbyc(), dataparser(), DB_process_UDP(), free_2darray(), free_2darray_l(), init_cfgparser(), main(), makecomtradecfg(), ncmp_cbyc(), and trimSpaces().
k
for k =1
Definition at line 51 of file convertComtrade.m.
Referenced by init_cfgparser(), makecomtradecfg(), and trimSpaces().
l
l = size(dat,2)
Definition at line 65 of file convertComtrade.m.
len
len = length(string)
Definition at line 130 of file convertComtrade.m.
Referenced by remove_old_cfg().
NR1
NR1 = Ana_Ch
Definition at line 61 of file convertComtrade.m.
NR2
if NR2 = ceil(Dig_Ch/16)
Definition at line 62 of file convertComtrade.m.
out
function out
Initial value:
= flinescan(rem,dlm)
    k = 1
Definition at line 120 of file convertComtrade.m.
PathAndCfgName
PathAndCfgName =[Path CfgFileName]
Definition at line 31 of file convertComtrade.m.
PathAndDatName
else PathAndDatName =[Path DatFileName]
Definition at line 33 of file convertComtrade.m.
rem
rem = strtok_singleDlm(rem,dlm)
Definition at line 123 of file convertComtrade.m.
remainder
remainder = string(finish +1:len)
Definition at line 142 of file convertComtrade.m.
start
end start = i
Definition at line 135 of file convertComtrade.m.
temp_string
while temp_string = fgetl(cfg_id)
Definition at line 53 of file convertComtrade.m.
token
token = string(start:finish)
Definition at line 141 of file convertComtrade.m.