iPDC - (Phasor Data Concentrator): dallocate.h File Reference
dallocate.h File Reference
Functions
void free_cfgframe_object (struct cfg_frame *cfg)
void free_dataframe_object (struct data_frame *)
void free_2darray (unsigned char **array, int x)
void myfree (void *ptr)
Function Documentation
free_2darray()
void free_2darray (unsigned char ** array, int n)
FUNCTION free_2darray:
It frees memory allocated to 2D Arrays.
Definition at line 162 of file dallocate.c.
{
         int i;
         for(i = 0; i < n; i++)
                 free(array[i]);
         free(array);
 }
Referenced by free_cfgframe_object(), and free_dataframe_object().
free_cfgframe_object()
void free_cfgframe_object (struct cfg_frame * cfg)
FUNCTION free_cfgframe_object():
It frees memory allocated to cfg objects.
Definition at line 53 of file dallocate.c.
{
         int j = 0;
         unsigned int phn,ann,dgn,num_pmu;
         struct dgnames *t_dgnames,*r_dgnames;
         num_pmu = to_intconvertor(cfg->num_pmu);
         while(j<num_pmu) {
                 free(cfg->pmu[j]->stn);
                 free(cfg->pmu[j]->idcode);
                 free(cfg->pmu[j]->data_format);
                 free(cfg->pmu[j]->fmt);
                 // Extract PHNMR, DGNMR, ANNMR
                 phn = to_intconvertor(cfg->pmu[j]->phnmr);
                 ann = to_intconvertor(cfg->pmu[j]->annmr);
                 dgn = to_intconvertor(cfg->pmu[j]->dgnmr);
                 if(phn != 0)
                         free_2darray(cfg->pmu[j]->cnext->phnames,phn);
                 if(ann != 0)
                         free_2darray(cfg->pmu[j]->cnext->angnames,ann);
                 if(dgn != 0) {
                         t_dgnames = cfg->pmu[j]->cnext->first;
                         while(t_dgnames != NULL) {
                                 r_dgnames = t_dgnames->dg_next;
                                 free_2darray(t_dgnames->dgn,16);
                                 t_dgnames = r_dgnames;
                         }
                 }
                 if(phn != 0)
                         free_2darray(cfg->pmu[j]->phunit,phn);
                 if(ann != 0)
                         free_2darray(cfg->pmu[j]->anunit,ann);
                 if(dgn != 0)
                         free_2darray(cfg->pmu[j]->dgunit,dgn);
                 free(cfg->pmu[j]->phnmr);
                 free(cfg->pmu[j]->annmr);
                 free(cfg->pmu[j]->dgnmr);
                 free(cfg->pmu[j]->fnom);
                 free(cfg->pmu[j]->cfg_cnt);
                 j++;
         } // End of While
         free(cfg->framesize);
         free(cfg->idcode);
         free(cfg->soc);
         free(cfg->fracsec);
         free(cfg->time_base);
         free(cfg->data_rate);
         free(cfg->num_pmu);
         free(cfg);
 }
References channel_names::angnames, for_each_pmu::annmr, for_each_pmu::anunit, for_each_pmu::cfg_cnt, for_each_pmu::cnext, for_each_pmu::data_format, cfg_frame::data_rate, dgnames::dg_next, dgnames::dgn, for_each_pmu::dgnmr, for_each_pmu::dgunit, channel_names::first, for_each_pmu::fmt, for_each_pmu::fnom, cfg_frame::fracsec, cfg_frame::framesize, free_2darray(), cfg_frame::idcode, for_each_pmu::idcode, cfg_frame::num_pmu, channel_names::phnames, for_each_pmu::phnmr, for_each_pmu::phunit, cfg_frame::pmu, cfg_frame::soc, for_each_pmu::stn, cfg_frame::time_base, and to_intconvertor().
Referenced by cfgparser(), and remove_llnode().
free_dataframe_object()
void free_dataframe_object (struct data_frame * df)
FUNCTION free_dataframe_object():
It frees memory allocated to data objects.
Definition at line 120 of file dallocate.c.
{
         int j = 0;
         // Free the blocks
         while(j < df->num_pmu) {
 //    Removed by Rajeev and Gopal. Following was leading to memory leak
 //    for the scneario, where MSB of stat flag was set to F. 29/08/2014
 //              if(df->dpmu[j]->stat[1] == 0x0F) {
 //
 //                      free(df->dpmu[j]->stat);
 //                      j++;
 //                      continue;
 //              }
                 free(df->dpmu[j]->stat);
                 free(df->dpmu[j]->freq);
                 free(df->dpmu[j]->dfreq);
                 free(df->dpmu[j]->fmt); // Added by gopal on 2014-08-30
                 if(df->dpmu[j]->phnmr != 0)
                         free_2darray(df->dpmu[j]->phasors,df->dpmu[j]->phnmr);
                 if(df->dpmu[j]->annmr != 0)
                         free_2darray(df->dpmu[j]->analog,df->dpmu[j]->annmr);
                 if(df->dpmu[j]->dgnmr != 0)
                         free_2darray(df->dpmu[j]->digital,df->dpmu[j]->dgnmr);
                 myfree(df->dpmu[j]); //added by gopal on 2013-12-22
                 j++;
         } // End of While
     myfree(df->dpmu); //added by gopal on 2013-12-22
         free(df->framesize);
         free(df->idcode);
         free(df->soc);
         free(df->fracsec);
         free(df);
 }
References data_for_each_pmu::analog, data_for_each_pmu::annmr, data_for_each_pmu::dfreq, data_for_each_pmu::dgnmr, data_for_each_pmu::digital, data_frame::dpmu, data_for_each_pmu::fmt, data_frame::fracsec, data_frame::framesize, free_2darray(), data_for_each_pmu::freq, data_frame::idcode, myfree(), data_for_each_pmu::phasors, data_for_each_pmu::phnmr, data_frame::soc, and data_for_each_pmu::stat.
Referenced by assign_df_to_TSB(), clear_TSB(), and time_align().
myfree()
void myfree (void * ptr)
Definition at line 170 of file dallocate.c.
 {
         if (ptr)
                 free(ptr);
 }
Referenced by free_dataframe_object(), and time_align().