iPDC - (Phasor Data Concentrator): ipdc.c File Reference
ipdc.c File Reference
#include <stdio.h>
#include <signal.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <sys/stat.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <errno.h>
#include <sys/types.h>
#include <unistd.h>
#include <pthread.h>
#include <gtk/gtk.h>
#include "connections.h"
#include "parser.h"
#include "global.h"
#include "ipdcGui.h"
Macros
#define GW(name) CH_GET_WIDGET(builder, name, data)
Functions
int main (int argc, char **argv)
Macro Definition Documentation
GW
#define GW (name) CH_GET_WIDGET(builder, name, data)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 57 of file ipdc.c.
 {
         /* local variables */
         int err;
         char *ptr1;
         struct stat st;
         memset(tname,'\0',20);
         strcpy(tname,"/dev/pts/");
         GtkBuilder *builder;
         GError     *error = NULL;
         PDC_IDCODE = 0;
         system("clear");
         /* Init GTK+ */
         gtk_init(&argc, &argv);
         /* Create new GtkBuilder object */
         builder = gtk_builder_new();
         char* UI_FILE_DIR = getenv("iPDC_UI_DIR");
         char UI_FILE[50];
         strcpy(UI_FILE, UI_FILE_DIR);
         strcat(UI_FILE,"/iPDC.xml");
         if(!gtk_builder_add_from_file(builder, UI_FILE, &error))
         {
                 g_warning("%s", error->message);
                 g_free(error);
                 return(1);
         }
         /* Allocate data structure */
         data = g_slice_new(ChData);
         /* Get objects from UI */
         #define GW(name) CH_GET_WIDGET(builder, name, data)
                 GW(ipdc);
                 GW(add_pmu_button);
                 GW(remove_pmu_button);
                 GW(cmd_data_off_button);
                 GW(cmd_data_on_button);
                 GW(cmd_cfg_button);
                 GW(cmd_inst_button);
                 GW(add_pdc_button);
                 GW(remove_pdc_button);
                 GW(display_conn_table_button);
                 GW(enter_pdc_detail_menuitem);
                 GW(exit_button);
                 GW(menubar);
                 GW(menuitem2);
                 GW(open_ipdc_setup);
                 GW(pdc_details_menuitem);
                 GW(menu_add_source);
                 GW(menu_remove_source);
                 GW(menu_data_off);
                 GW(menu_data_on);
                 GW(menu_request_cfg);
                 GW(menu_add_destination);
                 GW(menu_remove_destination);
                 GW(menu_conn_table);
                 GW(about_menuitem);
                 GW(exit_menuitem);
                 GW(text_view);
                 GW(text_view1);
                 GW(rights_label);
                 GW(admin_label);
                 GW(time_lable);
         #undef GW
         /* Connect signals */
         gtk_builder_connect_signals(builder, data);
         gtk_builder_connect_signals(builder, NULL);
      // Changes how a toplevel window deals with its size request and user resize attempts.
      gtk_window_set_policy (GTK_WINDOW (data->ipdc), FALSE, TRUE, TRUE);
      gtk_window_set_position(GTK_WINDOW(data->ipdc), GTK_WIN_POS_CENTER);
          char LOGO_FILE[50];
          strcpy(LOGO_FILE, UI_FILE_DIR);
          strcat(LOGO_FILE,"/logo.png");
 //     gtk_window_set_icon(GTK_WINDOW(data->ipdc), create_pixbuf(strcat(getenv("iPDC_UI_DIR"),"/ogo.png")));
      gtk_window_set_icon(GTK_WINDOW(data->ipdc), create_pixbuf( LOGO_FILE ));
      /* Set the Title of Main Window */
         gtk_window_set_title (GTK_WINDOW (data->ipdc), "iPDC");
         /* Disable all the (mentioned) buttons on main ipdc window */
         gtk_widget_set_sensitive(GTK_WIDGET(data->add_pmu_button), FALSE);
         gtk_widget_set_sensitive(GTK_WIDGET(data->remove_pmu_button), FALSE);
         gtk_widget_set_sensitive(GTK_WIDGET(data->cmd_data_off_button), FALSE);
         gtk_widget_set_sensitive(GTK_WIDGET(data->cmd_data_on_button), FALSE);
         gtk_widget_set_sensitive(GTK_WIDGET(data->cmd_cfg_button), FALSE);
         gtk_widget_set_sensitive(GTK_WIDGET(data->cmd_inst_button), FALSE);
         gtk_widget_set_sensitive(GTK_WIDGET(data->add_pdc_button), FALSE);
         gtk_widget_set_sensitive(GTK_WIDGET(data->remove_pdc_button), FALSE);
         gtk_widget_set_sensitive(GTK_WIDGET(data->display_conn_table_button), FALSE);
         gtk_widget_set_visible(GTK_WIDGET(data->menuitem2), FALSE);
         gtk_widget_set_visible(GTK_WIDGET(data->menu_conn_table), FALSE);
         gtk_widget_set_visible(GTK_WIDGET(data->pdc_details_menuitem), FALSE);
         memset(ipdcFilePath, '\0', 200);
         ptr1 = malloc(200*sizeof(char));
         memset(ptr1, '\0', 200);
         /* Get the user's name for storing the iPDC Setup File */
         strcpy(ptr1,getenv ("HOME"));
         if (ptr1 == NULL)
         {
                 printf("user not found\n");
                 exit(1);
         }
         strcat(ptr1, "/iPDC");
         if(stat(ptr1,&st) == 0) /* If main iPDC folder not present in the system? */
         {
                 strcat(ptr1, "/iPDC");
                 if(stat(ptr1,&st) == 0)
                 {
                         strcat(ipdcFolderPath, ptr1);
                         FILE * output;
                         int check;
                         char buff[200], is_empty[100];
                         strcpy(buff, "ls ");
                         strcat(buff, ipdcFolderPath);
                         strcat(buff, " | wc -l");
                         output = popen(buff,"r");
                         fgets (is_empty, 100, output); //write to the char
                         pclose (output);
                         check = atoi(is_empty);
                         if (check == 0) //No Setup files are present
{
                                 gtk_widget_set_visible(GTK_WIDGET(data->open_ipdc_setup), FALSE);
                                 /* fill the iPDC details */
                                 fill_pdc_details (NULL);
                         }
                         else
{
                                 char ch[300];
                                 //ptr1 = getenv ("HOME");
                                 strcpy(ch, "Fill the iPDC setup details manualy or open the iPDC setup file\nfrom the ");
                                 //strcat(ch, ptr1);
                                 //strcat(ch, "/");
                                 strcat(ch, ipdcFolderPath);
                                 //validation_result (ch);
                         }
                 }
                 else
                 {
                         if (mkdir (ptr1, 0700))
{
                                 printf ("Cannot create directory `%s': %s\n", ipdcFolderPath, strerror (errno));
                                 validation_result ("Cannot create iPDC directory on proposed path! ");
                         }
                         else
{
                                 strcat(ipdcFolderPath, ptr1);
                                 gtk_widget_set_visible(GTK_WIDGET(data->open_ipdc_setup), FALSE);
                                 /* fill the iPDC details */
                                 fill_pdc_details (NULL);
                         }
                 }
         }
         else
         {
                 if (mkdir (ptr1, 0700))
                 {
                         printf ("Cannot create directory `%s': %s", ipdcFolderPath, strerror (errno));
                         validation_result ("Cannot create iPDC directory on proposed path! ");
                 }
                 else
                 {
                         strcat(ptr1, "/iPDC");
                         if (mkdir (ptr1, 0700))
{
                                 printf ("Cannot create directory `%s': %s", ipdcFolderPath, strerror (errno));
                                 validation_result ("Cannot create iPDC sub-directory on proposed path! ");
                         }
                         else
{
                                 strcat(ipdcFolderPath, ptr1);
                                 gtk_widget_set_visible(GTK_WIDGET(data->open_ipdc_setup), FALSE);
                                 /* fill the iPDC details */
                                 fill_pdc_details (NULL);
                         }
                 }
         }
         /* Decorate the main window of iPDC */
         ipdc_colors();
         /* Signals Definitions*/
         g_signal_connect (data->add_pmu_button, "clicked", G_CALLBACK(add_pmu), NULL);
         g_signal_connect (data->menu_add_source, "activate", G_CALLBACK(add_pmu), NULL);
         g_signal_connect (data->remove_pmu_button, "clicked", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "1");
         g_signal_connect (data->menu_remove_source, "activate", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "1");
         g_signal_connect (data->cmd_data_off_button, "clicked", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "2");
         g_signal_connect (data->menu_data_off, "activate", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "2");
         g_signal_connect (data->cmd_data_on_button, "clicked", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "3");
         g_signal_connect (data->menu_data_on, "activate", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "3");
         g_signal_connect (data->cmd_cfg_button, "clicked", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "4");
         g_signal_connect (data->menu_request_cfg, "activate", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "4");
         g_signal_connect (data->cmd_inst_button, "clicked", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "5");
         g_signal_connect (data->menu_request_inst, "activate", G_CALLBACK(cmd_or_remove_pmu), (gpointer) "5");
         g_signal_connect (data->add_pdc_button, "clicked", G_CALLBACK(add_new_pdc), NULL);
         g_signal_connect (data->menu_add_destination, "activate", G_CALLBACK(add_new_pdc), NULL);
         g_signal_connect (data->remove_pdc_button, "clicked", G_CALLBACK(remove_pdc), NULL);
         g_signal_connect (data->menu_remove_destination, "activate", G_CALLBACK(remove_pdc), NULL);
         g_signal_connect (data->display_conn_table_button, "clicked", G_CALLBACK(connection_table), NULL);
         g_signal_connect (data->menu_conn_table, "activate", G_CALLBACK(connection_table), NULL);
         g_signal_connect (data->exit_button, "clicked", G_CALLBACK(destroy), NULL);
         g_signal_connect (data->open_ipdc_setup, "activate", G_CALLBACK(ipdc_setup_fileSelector), NULL);
         g_signal_connect (data->pdc_details_menuitem, "activate", G_CALLBACK(display_pdc_detail), NULL);
         g_signal_connect_swapped (data->enter_pdc_detail_menuitem, "activate", G_CALLBACK(fill_pdc_details), NULL);
         g_signal_connect (data->exit_menuitem, "activate", G_CALLBACK(destroy), NULL);
         g_signal_connect (data->about_menuitem, "activate", G_CALLBACK(about_ipdc), NULL);
         g_signal_connect (data->ipdc, "destroy", G_CALLBACK(destroy), NULL);
         /* Destroy builder, since we don't need it anymore */
         g_object_unref(G_OBJECT(builder));
         /* Show window. All other widgets are automatically shown by GtkBuilder */
         gtk_widget_show(data->ipdc);
         pthread_t t;
         if((err = pthread_create(&t,NULL,display_time,NULL)))
      {
                 perror(strerror(err));
                 exit(1);
         }
         if (argc > 1)
     {
         apply_ipdc_setup_arg (argc, argv);
     }
         /* GTK Main */
         gtk_main();
         pthread_join(UDP_thread, NULL);
         pthread_join(TCP_thread, NULL);
         pthread_join(DB_thread, NULL);
         pthread_join(p_thread, NULL);
 //      pthread_join(t, NULL);
         close(UL_UDP_sockfd);
         close(UL_TCP_sockfd);
         /* Free any allocated data */
         g_slice_free(ChData, data);
         return(0);
 }
References about_ipdc(), _ChData::about_menuitem, add_new_pdc(), _ChData::add_pdc_button, add_pmu(), _ChData::add_pmu_button, apply_ipdc_setup_arg(), buff, _ChData::cmd_cfg_button, _ChData::cmd_data_off_button, _ChData::cmd_data_on_button, _ChData::cmd_inst_button, cmd_or_remove_pmu(), connection_table(), create_pixbuf(), data, DB_thread, destroy(), _ChData::display_conn_table_button, display_pdc_detail(), display_time(), _ChData::enter_pdc_detail_menuitem, _ChData::exit_button, _ChData::exit_menuitem, fill_pdc_details(), GW, _ChData::ipdc, ipdc_colors(), ipdc_setup_fileSelector(), ipdcFilePath, ipdcFolderPath, _ChData::menu_add_destination, _ChData::menu_add_source, _ChData::menu_conn_table, _ChData::menu_data_off, _ChData::menu_data_on, _ChData::menu_remove_destination, _ChData::menu_remove_source, _ChData::menu_request_cfg, _ChData::menu_request_inst, _ChData::menuitem2, _ChData::open_ipdc_setup, p_thread, _ChData::pdc_details_menuitem, PDC_IDCODE, remove_pdc(), _ChData::remove_pdc_button, _ChData::remove_pmu_button, TCP_thread, tname, UDP_thread, UL_TCP_sockfd, UL_UDP_sockfd, and validation_result().