iPDC - (Phasor Data Concentrator): connections.c File Reference
connections.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/wait.h>
#include <signal.h>
#include <pthread.h>
#include "connections.h"
#include "parser.h"
#include "global.h"
Functions
void setup ()
void DB_udp ()
void * DB_udphandler (void *udp_BUF)
void DB_process_UDP (unsigned char *udp_BUF)
Variables
pthread_mutex_t mutex_on_buffer
Function Documentation
DB_process_UDP()
void DB_process_UDP (unsigned char * udp_BUF)
FUNCTION process_UDP():
This function Processes the frames as per their type(command, data, config).
Definition at line 266 of file connections.c.
{
         int stat_status,i;
         unsigned char c = udp_BUF[1];
         c <<= 1;
         c >>= 5;
         if(c == 0x00){                                  /* If data frame */
                 //printf("\nData frame reveived\n");
         if (cfgInProcess == 0)
         {
                 stat_status = dataparser(udp_BUF);
         }
         //printf("Return from Data Parser\n");
         } else if(c == 0x03) {                  /* If configuration frame */
                 printf("\nConfiguration frame reveived\n");
         cfgInProcess = 1; // A flag to capture that DB is engaged in prosessing the CFG data.
                 cfgparser(udp_BUF);
         cfgInProcess = 0; // A flag to capture that DB is engaged in prosessing the CFG data.
                 printf("Return from CFG\n");
         } else {
                 printf("Erroneous frame\n");
         }
         fflush(stdout);
 }
References cfgInProcess, cfgparser(), dataparser(), and i.
Referenced by DB_udphandler().
DB_udp()
void DB_udp ()
FUNCTION udp():
It creates a Pthread for each received UDP data.
Definition at line 166 of file connections.c.
              {
         // UDP threads are created for each received UDP message in 'detached' mode. Thus allowing any number of threads to be created.
         int err;
         pthread_attr_t attr;
         pthread_attr_init(&attr);
     if((err = pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED))) { // In  the detached state, the thread resources are
         // immediately freed when it terminates, but
         perror(strerror(err));                                          // pthread_join(3) cannot be used to synchronize
         exit(1);                                                        //  on the thread termination.
     }
         if((err = pthread_attr_setschedpolicy(&attr,SCHED_FIFO))) { // Shed policy = SCHED_FIFO (realtime, first-in first-out)
                 perror(strerror(err));
                 exit(1);
         }
         /* UDP data Received */
         while(1) {
                 if ((numbytes = recvfrom(DB_sockfd,buffer, MAXBUFLEN-1, 0,(struct sockaddr *)&their_addr, (socklen_t *)&DB_addr_len)) == -1) {
                         // Main if
                         perror("recvfrom");
                         exit(1);
                 } else { /* New datagram has been received */
                         pthread_t t;
                         int tt;
                         unsigned char *udp_BUF;
                         udp_BUF = malloc(MAXBUFLEN*sizeof(unsigned char));
                         if(!udp_BUF) {
                                 printf("No space for udp_BUF\n");
                                 exit(1);
                         }
                         //printf("UDP Server got packet from %s\n",inet_ntoa(their_addr.sin_addr));
                         //printf("packet is %d bytes long.\n",numbytes);
                         buffer[numbytes] = '\0';
                         /* Copy the udp_buf data to a local variable */
                         pthread_mutex_lock(&mutex_on_buffer);
                         copy_cbyc(udp_BUF,buffer,numbytes+1);
                         memset(buffer, '\0', MAXBUFLEN);
                         pthread_mutex_unlock(&mutex_on_buffer);
                         /* Creates a new thread for each received UDP message */
                         if((tt = pthread_create(&t,&attr,DB_udphandler,(void *)udp_BUF))) {
                                 perror(strerror(tt));
                                 exit(1);
                         }
 //                struct timeval tv1, tv2;
 //               long local_soc, local_fsec,ms_diff,s_diff;
                /* Obtain the time of day, and convert it to a tm struct. */
 //               gettimeofday (&tv1, NULL);
 //            DB_udphandler(udp_BUF);
 //               gettimeofday (&tv2, NULL);
 //               s_diff = (tv2.tv_sec - tv1.tv_sec);
 //               ms_diff = (tv2.tv_usec - tv1.tv_usec);
 //               ms_diff = ((s_diff == 0) ? ((ms_diff > 0) ? ms_diff : -1*ms_diff) : ((s_diff == 1) ? (1000000-tv2.tv_usec+tv1.tv_usec) : ((1000000*(s_diff-1))+(1000000-tv2.tv_usec+tv1.tv_usec))));
 //               printf("%f \n",(float)ms_diff*1e-6);
                 } // Main if ends
         } // while ends
         pthread_attr_destroy(&attr);
 }
References buffer, copy_cbyc(), DB_addr_len, DB_sockfd, DB_udphandler(), MAXBUFLEN, mutex_on_buffer, numbytes, and their_addr.
Referenced by setup().
DB_udphandler()
void* DB_udphandler (void * udp_BUF)
FUNCTION udphandler():
It internally calls process_UDP().
Definition at line 251 of file connections.c.
{
         DB_process_UDP((unsigned char*)udp_BUF);
         free((unsigned char*)udp_BUF);
 //      pthread_exit(NULL); /* Exit the thread once the task is done. */
 }
References DB_process_UDP().
Referenced by DB_udp().
setup()
void setup ()
Definition at line 68 of file connections.c.
             {
 //      printf("Entering DBServer setup()\n");
         /* MySQL data base parameters */
 //      server = "localhost";
 //      user = "root";
 //      password = "root";      /* Change this password value, if not the same in your case? */
 //      database = "iPDC";
         /* MySQL data base connection */
 //      conn_data = mysql_init(NULL);
 //      conn_cfg = mysql_init(NULL);
 //      if(conn_data == NULL) {
 //              printf("No sufficient memory\n");
 //              exit(1);
 //      }
 //      if(conn_cfg == NULL) {
 //              printf("No sufficient memory\n");
 //              exit(1);
 //      }
         /* Connect to database */
 //      if (!mysql_real_connect(conn_data, server,
 //                      user, password, database, 0, NULL, 0)) {
 //              fprintf(stderr, "%s\n", mysql_error(conn_data));
 //              exit(1);
 //      }
 //      if (!mysql_real_connect(conn_cfg, server,
 //                      user, password, database, 0, NULL, 0)) {
 //              fprintf(stderr, "%s\n", mysql_error(conn_cfg));
 //              exit(1);
 //      }
         /* Create UDP socket and bind to port */
         int yes;
         if ((DB_sockfd = socket(AF_INET, SOCK_DGRAM, 0)) == -1) {
                 perror("socket");
                 exit(1);
         } else {
                 printf("DB Socket:Sucessfully created\n");
         }
         if (setsockopt(DB_sockfd,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof(int)) == -1) {
                 perror("setsockopt");
                 exit(1);
         }
         DB_server_addr.sin_family = AF_INET;            // host byte order
         DB_server_addr.sin_port = htons(DBPORT);        // short, network byte order
         DB_server_addr.sin_addr.s_addr = INADDR_ANY;    // automatically fill with my IP
         memset(&(DB_server_addr.sin_zero),'\0', 8);     // zero the rest of the struct
         if (bind(DB_sockfd, (struct sockaddr *)&DB_server_addr,
                         sizeof(DB_server_addr)) == -1) {
                 perror("bind");
                 exit(1);
         } else {
                 printf("DB Socket Bind :Sucessfull\n");
         }
         printf("\nDB Server Listening on port %d\n",DBPORT);
         DB_addr_len = sizeof(struct sockaddr);
     tStartArchive = 0;
     cfgInProcess = 0; // A flag to capture that DB is engaged in prosessing the CFG data.
         DB_udp();
     closefilestreams();
 //      mysql_close(conn_cfg);
 //      mysql_close(conn_data);
 }
References cfgInProcess, closefilestreams(), DB_addr_len, DB_sockfd, DB_udp(), DBPORT, and tStartArchive.
Referenced by main().
Variable Documentation
mutex_on_buffer
pthread_mutex_t mutex_on_buffer
Definition at line 62 of file connections.c.
Referenced by DB_udp().